export const Newrelease =[{img:"https://i.postimg.cc/Y0LHfnZw/AK.webp",name:"Anweshippinkandethum"},
                {img:"https://i.postimg.cc/DZYCR5wS/Damsel.jpg",name: "Damsel"},
                {img:"https://i.postimg.cc/nrdMPPcS/Bandidos.jpg",name:"Bandidos"},
                {img:"https://i.postimg.cc/ZRsCfQq7/Thesignal.jpg",name:"Thesignal"},
                {img:"https://i.postimg.cc/vm3rs3B9/Supersex.jpg",name:"Supersex"},
                {img:"https://i.postimg.cc/CMHqTcQK/Thegentelman.jpg",name:"Thegentelman"},
                {img:"https://i.postimg.cc/nrGj4GWT/MC.webp",name:"Merry Christmas"},
                {img:"https://i.postimg.cc/RCgnZXcV/queenoftears.jpg",name:"queenoftears"},
                {img:"https://i.postimg.cc/7Yp1qKkJ/TP.jpg",name:"Turning Point"},
                {img:"https://i.postimg.cc/RVrQBP96/Akillerparadox.jpg",name:"Akillerparadox"},
                {img:"https://i.postimg.cc/6ptr7y8B/berlin.jpg",name:"berlin"},
                {img:"https://i.postimg.cc/d1krMCxj/cocomelon.jpg",name:"Cocomelon"},
                {img:"https://i.postimg.cc/25XhXG25/fs.jpg",name:"Full Swing"},
                {img:"https://i.postimg.cc/s225cqP8/GMV.jpg",name:"Goodmorning Veronica"},
                {img:"https://i.postimg.cc/Prmbrmr6/wrong-side-of-tracks.jpg",name:"Wrong Side of Tracks"}];  

export const Epicworld  =[{img:"https://i.postimg.cc/CL6xGhb7/Avatar.jpg",name:"Avatarthelastairbender"},
                            {img:"https://i.postimg.cc/Df6ZzdZt/Strangerthings.jpg",name:"Strangerthings"},
                            {img:"https://i.postimg.cc/m2rr1z1h/Onepiece.jpg",name:"Onepiece"},
                            {img:"https://i.postimg.cc/d3sVBDWH/Sweet-tooth.jpg",name:"Sweet-tooth"},
                            {img:"https://i.postimg.cc/DZYCR5wS/Damsel.jpg",name:"Damsel"},
                            {img:"https://i.postimg.cc/MH9KrxNW/Thewitcher.jpg",name:"Thewitcher"},
                            {img:"https://i.postimg.cc/zGbXpsjr/Lockand-Key.jpg",name:"Lockand-Key"},
                            {img:"https://i.postimg.cc/vBLmf5vx/cursed.jpg",name:"cursed"},
                            {img:"https://i.postimg.cc/mgr57RTb/Mortal-Engine.webp",name:"Mortal Engine"},
                            {img:"https://i.postimg.cc/Dy6NWmkj/The-Adam-Project.jpg",name:"The Adam Project"},]                

export const Awardwinningtvshows  =[{img:"https://i.postimg.cc/d37sb41T/Breaking-Bad.webp",name:"Breaking Bad"},
                            {img:"https://i.postimg.cc/mDg2wbWj/Friends.webp",name:"Friends"},
                            {img:"https://i.postimg.cc/PxVfVBtj/Lupin.jpg",name:"Lupin"},
                            {img:"https://i.postimg.cc/zGYzQw1V/Moneyheist.jpg",name:"Moneyheist"},
                            {img:"https://i.postimg.cc/QCR8h19Y/Wednesday.jpg",name:"Wednesday"},
                            {img:"https://i.postimg.cc/nV5c4bRK/Sexeducation.jpg",name:"Sexeducation"},
                            {img:"https://i.postimg.cc/jjssxs2T/The-Uncanny-Counter.jpg",name:"The Uncanny Counter"},
                            {img:"https://i.postimg.cc/MKQZtPNC/Thewalkingdead.webp",name:"Thewalkingdead"},
                            {img:"https://i.postimg.cc/HLBTjf8y/Stranger-Things.jpg",name:"Strangerthings"},
                            {img:"https://i.postimg.cc/Z5Pbz9Tj/Glitch.jpg",name:"Glitch"},]

export const USfantasyTV  =[{img:"https://i.postimg.cc/MH9KrxNW/Thewitcher.jpg",name:"Thewitcher"},
                            {img:"https://i.postimg.cc/d3sVBDWH/Sweet-tooth.jpg",name:"Sweet Tooth"},
                            {img:"https://i.postimg.cc/HLBTjf8y/Stranger-Things.jpg",name:"Strangerthings"},
                            {img:"https://i.postimg.cc/CL6xGhb7/Avatar.jpg",name:"Avatarthelastairbender"},
                            {img:"https://i.postimg.cc/CLd1fCj2/Onepiece.jpg",name:"Onepiece"},
                            {img:"https://i.postimg.cc/d0RtK5Yh/lucifer.jpg",name:"Lucifer"},
                            {img:"https://i.postimg.cc/bJ3yZdd8/First-Kill.jpg",name:"First Kill"},
                            {img:"https://i.postimg.cc/d1qQQGs4/October-Faction.jpg",name:"October Faction"},
                            {img:"https://i.postimg.cc/KvVY7Kf8/The-sandman.jpg",name:"The Sandman"},
                            {img:"https://i.postimg.cc/PqnrcBBG/Vampire-Daries.webp",name:"The Vampire Diaries"},]

export const KoreanTVDramedies  =[{img:"https://i.postimg.cc/RV8YLtYh/Racket-boys.jpg",name:"Racket boys"},
                            {img:"https://i.postimg.cc/kXDZSsfL/Its-okay-to-not-be-okay.jpg",name:"Its okay to not be okay"},
                            {img:"https://i.postimg.cc/RhZYXL96/iamnot-a-robot.webp",name:"iam not a robot"},
                            {img:"https://i.postimg.cc/sXc8YNFC/Mr-queen.webp",name:"Mr queen"},
                            {img:"https://i.postimg.cc/qqD5Y6Mm/Police-University.webp",name:"Police University"},
                            {img:"https://i.postimg.cc/xj6hqhyK/Stronggirlbongsoon.webp",name:"Stronggirlbongsoon"},
                            {img:"https://i.postimg.cc/tgg20Cww/Alchemy-of-Souls.jpg",name:"Alchemy-of-Souls"},
                            {img:"https://i.postimg.cc/fbg5MQhL/HI-BYE-MAMA.jpg",name:"HI-BYE-MAMA"},
                            {img:"https://i.postimg.cc/9QCLpBpW/Mylovefromstar.webp",name:"Mylovefromstar"},
                            {img:"https://i.postimg.cc/13BJYNCD/reply-1988.webp",name:"reply-1988"},
                            {img:"https://i.postimg.cc/B6Lp67qC/Vincenzo.jpg",name:"Vincenzo"}]

export const criticallyacclaimedtvshow  =[{img:"https://i.postimg.cc/1zRYFbjp/Alice-in-borderland.jpg",name:"Alice-in-borderland"},
                            {img:"https://i.postimg.cc/XNrmQS7L/Archieve81.jpg",name:"Archieve81"},
                            {img:"https://i.postimg.cc/SQH5PTnh/Black-Lighting.webp",name:"Black-Lighting"},
                            {img:"https://i.postimg.cc/0QQd5sHB/Black-mirror.jpg",name:"Black-mirror"},
                            {img:"https://i.postimg.cc/NLh1xrG3/Dark.jpg",name:"Dark"},
                            {img:"https://i.postimg.cc/bvL9jJLn/dirty-gentle.jpg",name:"dirty-gentle"},
                            {img:"https://i.postimg.cc/7Y7cr3zT/Glitch.jpg",name:"Glitch"},
                            {img:"https://i.postimg.cc/850dj02P/Lovedeathrobot.jpg",name:"Lovedeathrobot"},
                            {img:"https://i.postimg.cc/GtTFYjRP/The-innocents.jpg",name:"The-innocents"},
                            {img:"https://i.postimg.cc/kgmHJ2NY/The-umberlla-academy.jpg",name:"The-umberlla-academy"},
                            {img:"https://i.postimg.cc/13rjfyJm/Titan.jpg",name:"Titan"}]

export const TVactiondndadventure  =[{img:"https://i.postimg.cc/5trKWqwh/Blue-eye-Samurai.jpg",name:"Blue-eye-Samurai"},
                            {img:"https://i.postimg.cc/qqVmzJDQ/House-of-Ninjas.jpg",name:"House-of-Ninjas"},
                            {img:"https://i.postimg.cc/T3R4VPd4/Cobra-Kai.jpg",name:"Cobra-Kai"},
                            {img:"https://i.postimg.cc/6qrMZkDK/Fauda.jpg",name:"Fauda"},
                            {img:"https://i.postimg.cc/kgmHJ2NY/The-umberlla-academy.jpg",name:"The-umberlla-academy"},
                            {img:"https://i.postimg.cc/6ptr7y8B/berlin.jpg",name:"berlin"},
                            {img:"https://i.postimg.cc/XJyHjGLp/Lostinspace.jpg",name:"Lostinspace"},
                            {img:"https://i.postimg.cc/mrkpn6F3/Vikings.webp",name:"Lovedeathrobot"},
                            {img:"https://i.postimg.cc/PxVfVBtj/Lupin.jpg",name:"Lupin"},
                            {img:"https://i.postimg.cc/zGYzQw1V/Moneyheist.jpg",name:"Moneyheist"}]

export const TVDRAMA  =[{img:"https://i.postimg.cc/htRNvq32/13reasonswhy.jpg",name:"13reasonswhy"},
                            {img:"https://i.postimg.cc/7hTQPB1v/Better-call-saul.webp",name:"Better-call-saul"},
                            {img:"https://i.postimg.cc/SQ5B09LF/Emily-in-paris.jpg",name:"Emily-in-paris"},
                            {img:"https://i.postimg.cc/L4YHZ2NS/gyeongsyeongcreature.jpg",name:"gyeongsyeongcreature"},
                            {img:"https://i.postimg.cc/z3Z2ynpy/kaalapaani.jpg",name:"kaalapaani"},
                            {img:"https://i.postimg.cc/nhkZtzc4/Legendofthebluesea.webp",name:"Legendofthebluesea"},
                            {img:"https://i.postimg.cc/xjw9vh4z/Luz.jpg",name:"Luz"},
                            {img:"https://i.postimg.cc/NfRBpD3P/My-Life-with-Water-Boys.jpg",name:"My-Life-with-Water-Boys"},
                            {img:"https://i.postimg.cc/q7vrBTz9/Squidgame.jpg",name:"Squidgame"},
                            {img:"https://i.postimg.cc/MGW40mwR/sweethome.jpg",name:"sweethome"},
                            {img:"https://i.postimg.cc/FHmmqcmF/The-glory.jpg",name:"The-glory.jpg"},
                            {img:"https://i.postimg.cc/tTcMj0xt/Xokitty.jpg",name:"Xokitty"}]

export const TVTHRILLER  =[{img:"https://i.postimg.cc/Hs16pJ7j/CAT.jpg",name:"13reasonswhy"},
                            {img:"https://i.postimg.cc/J43Pt1bx/Fauda.jpg",name:"Better-call-saul"},
                            {img:"https://i.postimg.cc/q7qLmyWD/the-night-agent.jpg",name:"Emily-in-paris"},
                            {img:"https://i.postimg.cc/HkBz4Bv7/Locked-up.jpg",name:"gyeongsyeongcreature"},
                            {img:"https://i.postimg.cc/fRw596CN/OZARK.jpg",name:"kaalapaani"},
                            {img:"https://i.postimg.cc/9FNtDrDG/1899.jpg",name:"Legendofthebluesea"},
                            {img:"https://i.postimg.cc/RV0LCcZS/Dark-2.jpg",name:"Luz"},
                            {img:"https://i.postimg.cc/3r1ZHL7f/snowpiercer.jpg",name:"My-Life-with-Water-Boys"},
                            {img:"https://i.postimg.cc/3RSC2RL5/Elite.jpg",name:"Squidgame"},
                            {img:"https://i.postimg.cc/J0s3xLgy/Money-heist-Korea.jpg",name:"sweethome"},
                            {img:"https://i.postimg.cc/z3Z2ynpy/kaalapaani.jpg",name:"The-glory.jpg"}]

export const TOP10INDIA  =[{imgtv:"https://i.postimg.cc/zGWKtpff/1.jpg",imgmovie:"https://i.postimg.cc/k4tH7tRQ/1movie.jpg",imgno:"https://i.postimg.cc/YCVY8Z7Z/image00001.png"},
                            {imgtv:"https://i.postimg.cc/5jcyWHyr/2.jpg",imgmovie:"https://i.postimg.cc/527Kvmw5/2movie.jpg",imgno:"https://i.postimg.cc/rsCjLjH7/image00002.png"},
                            {imgtv:"https://i.postimg.cc/66FfpYGk/3.jpg",imgmovie:"https://i.postimg.cc/X7WP0qj5/3movie.webp",imgno:"https://i.postimg.cc/QdnbsH6N/image00003.png"},
                            {imgtv:"https://i.postimg.cc/MHfHL06R/4.jpg",imgmovie:"https://i.postimg.cc/vTFNTH5p/4movie.webp",imgno:"https://i.postimg.cc/kXcJLwRP/image00004.png"},
                            {imgtv:"https://i.postimg.cc/05zCvLrG/5.jpg",imgmovie:"https://i.postimg.cc/J7ZFgZLm/5movie.webp",imgno:"https://i.postimg.cc/QtSVGWb0/image00005.png"},
                            {imgtv:"https://i.postimg.cc/4dSnw2gs/6.jpg",imgmovie:"https://i.postimg.cc/QCQnTGbV/6movie.webp",imgno:"https://i.postimg.cc/W4Yb5PbH/image00006.png"},
                            {imgtv:"https://i.postimg.cc/zfpyHX2L/7.jpg",imgmovie:"https://i.postimg.cc/jdhFqT2F/7movie.webp",imgno:"https://i.postimg.cc/26PjfFWd/image00007.png"},
                            {imgtv:"https://i.postimg.cc/q7pt7CwV/8.jpg",imgmovie:"https://i.postimg.cc/q7FYfGqB/8movie.webp",imgno:"https://i.postimg.cc/gJwc5Bxk/image00008.png"},
                            {imgtv:"https://i.postimg.cc/G22HFw6X/9.jpg",imgmovie:"https://i.postimg.cc/NjfP5nrf/9movie.jpg",imgno:"https://i.postimg.cc/qqyJBhcP/image00009.png"},
                            {imgtv:"https://i.postimg.cc/13GnPKpr/10.jpg",imgmovie:"https://i.postimg.cc/5tyGkrxk/10movie.jpg",imgno:"https://i.postimg.cc/pdLLQdxj/image00010.png"}]

